---
abstract: 'Client and worker libraries for gearman job dispatch dispatch.  Server is in separate package.'
author:
  - 'Brad Fitzpatrick <brad@danga.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.132510'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gearman
no_index:
  directory:
    - t
    - inc
requires:
  String::CRC32: 0
  Time::HiRes: 0
version: 1.12
