---
abstract: 'Client and worker libraries for gearman job dispatch dispatch.  Server is in separate package.'
author:
  - 'Brad Fitzpatrick <brad@danga.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gearman
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Errno: 0
  IO::Handle: 0
  IO::Socket::INET: 0
  Scalar::Util: 0
  Socket: 0
  Storable: 1
  String::CRC32: 0
  Time::HiRes: 0
  fields: 0
version: v1.12.002
